### ISSUE TITLE
Streamlining the blog posting process

### ISSUE THREAD

**Issue by leohhhn** [gnolang/blog#37]
@moul
cc @michelleellen @waymobetta @ccomben 

We've created a CONTRIBUTING.md, that will help streamline the process of submitting a new blog post. [PR](https://github.com/gnolang/blog/pull/36)

We've added a template PR, that people will be able to follow when they want to submit a new blog post. The PR is not to be merged, as it will serve as an example for the newcoming posts. [PR](https://github.com/gnolang/blog/pull/35)

Regarding the process of posting new blog posts itself, we aim to have @moul only look at the blog post as a final review, and deploy the post once it passes all checks. Afterwards, DevRel will take full responsibility of merging new posts into main, and publishing on-chain. 

We've two questions:
- We should set a standard for fields in the front matter. For example, the \<author>  is just a name, like `christina`. My suggestion would be to have it be GH usernames, or any other identifier that makes sense and can be traced. 
- We found a [thumbs.sh](https://github.com/gnolang/blog/blob/main/posts/thumbs.sh) that is not 100% clear to us. What is its purpose?

**Comment by ccomben** [comment]
@leohhhn I like the idea of using GitHub handles for the author. Would that appear on the actual blog, though? We haven't added author names on any content yet, as the official content is from Gno.land. It would be suitable for contributor and community posts, though.

**Comment by waymobetta** [comment]
Adding Github handles for the author names in the blog currently causes an error within the Markdown rendering, resolved by #45. We will investigate how to circumvent this error and still have links to the usernames, probably just by making the author names themselves hyperlinks and not using the `@` symbol.
