### ISSUE TITLE
Add Who You Gno – On the Record with Dongwon Shin

### ISSUE THREAD

**Issue by ccomben** [gnolang/blog#50]
# Who You Gno – On the Record with Dongwon Shin

@leohhhn @waymobetta 

I have a new [blog post](https://docs.google.com/document/d/1OPqwc36u2LE5xqZjSOiToq7dSYvmLfzRH9ak3FWMX6Q/edit) to add. I have done it in Markdown. Hopefully, it is right! Can you create the PR for it and let Manfred know when it's ready? 

Many thanks.

**Comment by waymobetta** [comment]
Github automation may not have worked because this should've been closed with #51
