### ISSUE TITLE
make gnoblog-cli extract the title from markdown and remove `title:` from frontmatter.

### ISSUE THREAD

**Issue by moul** [gnolang/blog#56]
Instead of setting the title as frontmatter metadata and manually removing the first markdown title (`#`), we should do the opposite. This will make things clearer, easier to review, and result in a better rendering of the source file on GitHub.

We can accomplish this in a single PR by updating gnoblog-cli to extract the title from the markdown and by updating existing blog posts to adhere to the new expected behavior.

**Comment by leohhhn** [comment]
Will be fixed in #63.

**Comment by leohhhn** [comment]
Closed by #63.
